Add database
RikkkiTikkkiTavi/java-filmorate pull request #11
Opened 2023-06-07 23:43 UTC by RikkkiTikkkiTavi

2023-06-08 21:41 UTC, sergeymamonov requested changes

2023-06-08 21:41 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>      }
В 73 строке выполняются запросы к БД в цикле. Не очень хорошо делать запросы к БД в цикле. Это большая нагрузка на БД. Затратно по времени из-за передачи по сети.

2023-06-08 21:41 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                jdbcTemplate.update(sqlQueryGenres,
Запросы к БД в цикле. Нужно избавиться от этого.

2023-06-08 21:41 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        Set<Genre> genres = new TreeSet<>(Comparator.comparingInt(Genre::getId));
TreeSet работает медленнее чем HashSet, поэтому таким решеним вы замедляете работу своего приложения, хотя необходимости в TreeSet здесь нет.

2023-06-08 21:41 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            Genre genre = new Genre();
Здесь вы конвертируете из одного объекта в другой, поэтому это нужно выделить в отдельный класс конвертер. Аналогично в остальных случаях.

2023-06-08 21:41 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +            jdbcTemplate.update(sqlQueryLikes,
Запросы к БД в цикле.

2023-06-08 21:41 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/validator/FilmValidator.java
> +    public static void checkId(List<Film> films, Film film) {
С БД так не работают, как с коллекцией. От аналогичных методов проверки по id полным сканированием нужно отказаться.

2023-06-08 21:41 UTC, sergeymamonov commented on src/main/resources/schema.sql
> +	MPA_NAME varchar NOT NULL,
Размер varchar должен быть ограничен.

2023-06-08 21:41 UTC, sergeymamonov commented on src/main/resources/schema.sql
> +ALTER TABLE FILMS ADD MPA_ID INTEGER;
Зачем изменять таблицу добавлением колонки, если можно сразу при создании таблицы создавать эту колонку.

2023-06-08 21:41 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/validator_test/FilmValidatorTest.java
> +        Film emptyNameFilm = Film.builder()
В каждом тесте создается фильм, это занимает много строк кода. Можно сделать метод с аннотацией @BeforeEach, который будет выполняться перед каждым тестом в этом классе. И в этом методе создать фильм. А в самом тесте через сеттер менять валидное поле на невалидное для этого теста. Аналогично и для других тестовых классов.

2023-06-11 16:33 UTC, sergeymamonov approved these changes
Посмотрите по поиску по проекту использование TreeSet. Действительно ли множество такого типа вам нужно? Возможно, можно обойтись HashSet. Если посмотрите внутреннее устройство этих множеств, то HashSet работает быстрее.

Посмотрите поиском по проекту конструкции builder().build() - это неверное использование паттерна билдер (см. замечание с предыдущего ревью).

2023-06-11 16:33 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public List<Mpa> findMPA() {
Здесь тоже нужно переименовать на Mpa.

2023-06-11 16:33 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                jdbcTemplate.update(sqlQueryGenres, film.getId(), genre.getId());
Запросы к БД в цикле.

2023-06-11 16:33 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        return Film.builder().id(resultSet.getInt("film_id")).name(resultSet.getString("name")).description(resultSet.getString("description")).releaseDate(resultSet.getDate("release_date").toLocalDa
Нужно стараться, чтобы длина строки не превосходила 120 символов. Поэтому здесь нужно переносить на новые строки.

2023-06-11 16:33 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        Mpa mpa = Mpa.builder().build();
Неверное использование паттерна билдер.

2023-06-11 16:35 UTC, sergeymamonov requested changes
Необходимо устранить замечания.

2023-06-12 00:31 UTC, RikkkiTikkkiTavi commented
Прощу прощения, часть скрытых замечаний не заметил с прошлого ревью.
Могу ли поинтересоваться? Какой теперь смысл в классах сервисах ибо логика ложится теперь на sql запросы? 
Какая логика будет закладываться в сервисы? Выносятся ли обычно методы получения сущностей в отдельный класс?
Спасибо за ревью.

2023-06-12 05:29 UTC, sergeymamonov approved these changes
Посмотрите TreeSet в проекте. Особенно в тестах. Поиск по проекту - Ctrl + Shift + F.

Что касается зачем нужны классы сервисов? Приложение выставляет наружу рест эндпоинты, слушает какие-то топики Кафки, например, соап энпоинты могут быть и так далее. От этих эндпоинтов или листенеров и т.д. идет вызов нужно метода сервиса. В сервисе делается вся необходимая логика (валидация, создание доменных объектов, формирование запросов в другие сервисы, необходимые запросы к БД (в разные БД) и так далее). Логика может быть достаточно обширная. А SQL запрос - это запрос для получения данных из БД. 
Выносятся ли обычно методы получения сущностей в отдельный класс? - тут не очень понял. Если что-то будет непонятно, то пишите в пачке.

2023-06-12 05:29 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/validator/FilmValidator.java
> +            film.setLikes(new TreeSet<>());
Здесь действительно нужен TreeSet?

2023-06-12 05:29 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/validator/FilmValidator.java
> +            film.setLikes(new TreeSet<>());
И вообще идея что-то сеттить в валидоре так себе. Логика должна быть в сервисе, а в валидаторе только проверки.

2023-06-12 19:13 UTC, merged