add new functionality
RikkkiTikkkiTavi/java-filmorate pull request #8
Opened 2023-05-16 22:39 UTC by RikkkiTikkkiTavi

2023-05-18 03:45 UTC, sergeymamonov requested changes

2023-05-18 03:45 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +}
Рекомендую еще добавить обработку ошибок в ходе выполнения, чтобы возвращалась 500 ошибка.

2023-05-18 03:45 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService service, InMemoryFilmStorage storage) {
Можно не писать конструктор руками, а воспользоваться аннотацией Lombok @AllArgsConstructor. Аналогично во всех местах, где можно заменить написанный руками конструктор.

2023-05-18 03:45 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return storage.findAll();
Неверно вызывать стораж из контроллера. Нужно вызывать метод сервиса. А уже в сервисе вызывается метод стоража. Это необходимо изменить во всех контроллерах.

2023-05-18 20:54 UTC, RikkkiTikkkiTavi commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +}
Данную рекомендацию немного не понял. Spring по умолчанию возвращает 500 при возникновении неизвестного исключения.

2023-05-19 04:15 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +}
@ExceptionHandler
	@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
	public ErrorResponse handleThrowable(final Throwable e) {
		log.info("500 {}", e.getMessage(), e);
		return new ErrorResponse(e.getMessage());
	}

2023-05-19 04:26 UTC, sergeymamonov approved these changes

2023-06-07 22:58 UTC, merged